-- MySQL Script generated by MySQL Workbench
-- jue 14 nov 2019 14:03:15 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table Viveros
-- -----------------------------------------------------
CREATE TABLE  Viveros (
  Coordenadas text NOT NULL,
  Localidad text NULL,
  PRIMARY KEY (Coordenadas));


-- -----------------------------------------------------
-- Table Zona
-- -----------------------------------------------------
CREATE TABLE  Zona (
  Nombre text NOT NULL,
  Coordenadas text NOT NULL REFERENCES Viveros(Coordenadas) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (Nombre, Coordenadas));

-- -----------------------------------------------------
-- Table Empleado
-- -----------------------------------------------------
CREATE TABLE  Empleado (
  DNI integer NOT NULL,
  Sueldo float(2) NULL,
  CSS integer NULL,
  Antiguedad DATE NULL,
  Ventas integer NULL,
  FechaIni DATE NOT NULL,
  FechaFin DATE NULL,
  Coordenadas text NULL REFERENCES Viveros(Coordenadas) ON DELETE CASCADE ON UPDATE CASCADE,
  Nombre text NULL REFERENCES Zona(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
  PRIMARY KEY (DNI, FechaIni));


-- -----------------------------------------------------
-- Table Cliente
-- -----------------------------------------------------
CREATE TABLE  Cliente (
  DNI integer NOT NULL,
  Bonus text NULL,
  CompraMensual float(2) NULL,
  PRIMARY KEY (DNI));


-- -----------------------------------------------------
-- Table Producto
-- -----------------------------------------------------
CREATE TABLE  Producto (
  CodProducto integer NOT NULL,
  Precio integer NULL,
  Stock integer NULL,
  PRIMARY KEY (CodProducto));


-- -----------------------------------------------------
-- Table ZonaProducto
-- -----------------------------------------------------
CREATE TABLE  ZonaProducto (
  Coordenadas text NOT NULL REFERENCES Viveros(Coordenadas) ON DELETE CASCADE ON UPDATE CASCADE,
  Nombre text NOT NULL REFERENCES Zona(Nombre) ON DELETE NO ACTION ON UPDATE CASCADE,
  CodProducto integer NOT NULL REFERENCES Producto(CodProducto) ON DELETE NO ACTION ON UPDATE CASCADE,
  StockZona integer NULL,
  PRIMARY KEY (Coordenadas, Nombre, CodProducto));


-- -----------------------------------------------------
-- Table ClienEmpleProd
-- -----------------------------------------------------
CREATE TABLE  ClienEmpleProd (
  DNIEmp integer NOT NULL REFERENCES Empleado(DNI) ON DELETE NO ACTION ON UPDATE CASCADE,
  DNIClien integer NOT NULL REFERENCES Cliente(DNI) ON DELETE NO ACTION ON UPDATE CASCADE,
  CodProducto integer NOT NULL REFERENCES Producto(CodProducto) ON DELETE NO ACTION ON UPDATE CASCADE,
  Fecha DATE NOT NULL,
  Cantidad integer NULL,
  FechaIni DATE NULL,
  PRIMARY KEY (DNIEmp, DNIClien, CodProducto, Fecha));


