-- MySQL Script generated by MySQL Workbench
-- jue 14 nov 2019 14:03:15 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table Viveros
-- -----------------------------------------------------
CREATE TABLE  Viveros (
  Coordenadas text NOT NULL,
  Localidad text NULL,
  PRIMARY KEY (Coordenadas));


-- -----------------------------------------------------
-- Table Zona
-- -----------------------------------------------------
CREATE TABLE  Zona (
  Nombre text NOT NULL,
  Coordenadas text NOT NULL REFERENCES Viveros(Coordenadas) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (Nombre, Coordenadas));

-- -----------------------------------------------------
-- Table Empleado
-- -----------------------------------------------------
CREATE TABLE  Empleado (
  DNI integer NOT NULL,
  Sueldo float(2) NULL,
  CSS integer NULL,
  Antiguedad DATE NULL,
  Ventas integer NULL,
  FechaIni DATE NOT NULL,
  FechaFin DATE NULL,
  Coordenadas text NULL,
  Nombre text NULL,
  PRIMARY KEY (DNI, FechaIni),
  FOREIGN KEY (Nombre, Coordenadas) REFERENCES Zona(Nombre,Coordenadas) ON DELETE CASCADE ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table Cliente
-- -----------------------------------------------------
CREATE TABLE  Cliente (
  DNI integer NOT NULL,
  Bonus text NULL,
  CompraMensual float(2) NULL,
  PRIMARY KEY (DNI));


-- -----------------------------------------------------
-- Table Producto
-- -----------------------------------------------------
CREATE TABLE  Producto (
  CodProducto integer NOT NULL,
  Precio integer NULL,
  Stock integer NULL,
  PRIMARY KEY (CodProducto));


-- -----------------------------------------------------
-- Table ZonaProducto
-- -----------------------------------------------------
CREATE TABLE  ZonaProducto (
  Coordenadas text NOT NULL,
  Nombre text NOT NULL,
  CodProducto integer NOT NULL REFERENCES Producto(CodProducto) ON DELETE RESTRICT ON UPDATE CASCADE,
  StockZona integer NULL,
  PRIMARY KEY (Coordenadas, Nombre, CodProducto),
  FOREIGN KEY (Nombre, Coordenadas) REFERENCES Zona(Nombre,Coordenadas) ON DELETE CASCADE ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table ClienEmpleProd
-- -----------------------------------------------------
CREATE TABLE  ClienEmpleProd (
  DNIEmp integer NOT NULL,
  DNIClien integer NOT NULL REFERENCES Cliente(DNI) ON DELETE RESTRICT ON UPDATE CASCADE,
  CodProducto integer NOT NULL REFERENCES Producto(CodProducto) ON DELETE RESTRICT ON UPDATE CASCADE,
  Fecha DATE NOT NULL,
  Cantidad integer NULL,
  FechaIni DATE NULL,
  PRIMARY KEY (DNIEmp, DNIClien, CodProducto, Fecha)
  FOREIGN KEY (DNIEmp,FechaIni) REFERENCES Empleado(DNI, FechaIni) ON DELETE RESTRICT ON UPDATE CASCADE);


