-- MySQL Script generated by MySQL Workbench
-- jue 21 nov 2019 12:48:48 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  proyecto  ;

CREATE TYPE direccion_postal AS (
  calle     text,
  numero    integerEGER,
  provincia text,
  cp        text
);

-- -----------------------------------------------------
-- Table Proyecto
-- -----------------------------------------------------
CREATE TABLE  Proyecto (
  Proyecto_id integer NOT NULL,
  Nombre text UNIQUE NULL,
  Fecha_fin DATE NULL,
  Dirigido_por integer NOT NULL REFERENCES Jefe de proyecto (Codigo_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (Proyecto_id));


-- -----------------------------------------------------
-- Table Jefe de proyecto
-- -----------------------------------------------------
CREATE TABLE  Jefe de proyecto (
  Codigo_id integer NOT NULL,
  Nombre text UNIQUE NULL,
  Telefono integer NULL,
  Direccion direccion_postal NULL,
  Dirige_proyecto integer NULL REFERENCES Proyecto (Proyecto_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (Codigo_id));


-- -----------------------------------------------------
-- Table Figura
-- -----------------------------------------------------
CREATE TABLE  Figura (
  Figura_id integer NOT NULL,
  Nombre text NULL,
  Color text NULL,
  Área float(2) NULL,
  PRIMARY KEY (Figura_id));


-- -----------------------------------------------------
-- Table Planos
-- -----------------------------------------------------
CREATE TABLE  Planos (
  Plano_id integer NOT NULL,
  Arquitectos text[] NULL,
  Num_figuras integer NULL,
  Fecha_entrega DATE NULL,
  Dibujo BLOB NULL,
  Proyecto_id integer NULL REFERENCES Proyecto (Proyecto_id) ON DELETE NO ACTION ON UPDATE CASCADE,
  Figura_id integer NULL REFERENCES Figura (Figura_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  PRIMARY KEY (Plano_id));


-- -----------------------------------------------------
-- Table Lineas
-- -----------------------------------------------------
CREATE TABLE  Lineas (
  Lineas_id integer NOT NULL,
  Origen_x float(2) NULL,
  Origen_y float(2) NULL,
  Fin_x float(2) NULL,
  Fin_y float(2) NULL,
  Longitud float(2) NULL,
  Poligono_id integer NULL,
  PRIMARY KEY (Lineas_id));


-- -----------------------------------------------------
-- Table Poligono
-- -----------------------------------------------------
CREATE TABLE  Poligono (
  Figura_id integer NOT NULL REFERENCES Figura (Figura_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  Num_lineas integer NULL,
  Lineas_id integer[] NULL REFERENCES Lineas (Lineas_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (Figura_id));


