-- MySQL Script generated by MySQL Workbench
-- mié 13 nov 2019 19:01:08 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "mydb"  ;

-- -----------------------------------------------------
-- Table "mydb"."Familia"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Familia" (
  "Nombre" VARCHAR(45) NOT NULL,
  "Incompatibilidades" VARCHAR(45) NULL,
  PRIMARY KEY ("Nombre"));


-- -----------------------------------------------------
-- Table "mydb"."Enfermedad"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Enfermedad" (
  "Nombre" VARCHAR(45) NOT NULL,
  "Síntoma" VARCHAR(45) NULL,
  PRIMARY KEY ("Nombre"));


-- -----------------------------------------------------
-- Table "mydb"."FamiliaEnfermedad"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."FamiliaEnfermedad" (
  "Nombre_fam" VARCHAR(45) NOT NULL,
  "Nombre_enf" VARCHAR(45) NOT NULL,
  PRIMARY KEY ("Nombre_fam", "Nombre_enf"),
  CONSTRAINT "fk_FamiliaEnfermedad_Fam"
    FOREIGN KEY ("Nombre_fam")
    REFERENCES "mydb"."Familia" ("Nombre")
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT "fk_FamiliaEnfermedad_Enf"
    FOREIGN KEY ("Nombre_enf")
    REFERENCES "mydb"."Enfermedad" ("Nombre")
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."Laboratio"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Laboratio" (
  "Código" INT NOT NULL,
  "Nombre" VARCHAR(45) NULL,
  "Contacto" VARCHAR(45) NULL,
  "Teléfono" INT NULL,
  "Calle" VARCHAR(45) NULL,
  "NúmCalle" INT NULL,
  "CP" INT NULL,
  PRIMARY KEY ("Código"));


-- -----------------------------------------------------
-- Table "mydb"."Medicamento"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Medicamento" (
  "Código" INT NOT NULL,
  "Nombre" VARCHAR(45) NULL,
  "Posología" VARCHAR(45) NULL,
  "Igic%" INT NULL,
  "Precio" INT NULL,
  "Tipo" BOOLEAN NOT NULL,
  "Laboratorio" INT NULL,
  PRIMARY KEY ("Código"),
  CONSTRAINT "fk_Medicamento_Labo"
    FOREIGN KEY ("Laboratorio")
    REFERENCES "mydb"."Laboratio" ("Código")
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."MedicamFamilia"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."MedicamFamilia" (
  "CódigoMed" INT NOT NULL,
  "NombreFam" VARCHAR(45) NOT NULL,
  PRIMARY KEY ("CódigoMed", "NombreFam"),
  CONSTRAINT "fk_MedicamFamilia_Medic"
    FOREIGN KEY ("CódigoMed")
    REFERENCES "mydb"."Medicamento" ("Código")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "fk_MedicamFamilia_Fam"
    FOREIGN KEY ("NombreFam")
    REFERENCES "mydb"."Familia" ("Nombre")
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."Compra"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Compra" (
  "FechaActual" TIMESTAMP NOT NULL,
  "Importe" INT NULL,
  PRIMARY KEY ("FechaActual"));


-- -----------------------------------------------------
-- Table "mydb"."MedicamCompra"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."MedicamCompra" (
  "CódigoMed" INT NOT NULL,
  "FechaActualCompra" TIMESTAMP NOT NULL,
  "Importe" FLOAT NULL,
  "Igic" FLOAT NULL,
  PRIMARY KEY ("CódigoMed", "FechaActualCompra"),
  CONSTRAINT "fk_MedicamCompra_Cód"
    FOREIGN KEY ("CódigoMed")
    REFERENCES "mydb"."Medicamento" ("Código")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_MedicamCompra_Fecha"
    FOREIGN KEY ("FechaActualCompra")
    REFERENCES "mydb"."Compra" ("FechaActual")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "mydb"."ClienteCred"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."ClienteCred" (
  "CC" VARCHAR(30) NOT NULL,
  "Nombre" VARCHAR(45) NULL,
  "DíaPago" INT NULL,
  PRIMARY KEY ("CC"));


-- -----------------------------------------------------
-- Table "mydb"."PagoCréd"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."PagoCréd" (
  "Mes" INT NOT NULL,
  "Año" INT NOT NULL,
  "FechaActualCompra" TIMESTAMP NOT NULL,
  "FechaPago" TIMESTAMP NULL,
  "CantidadPago" FLOAT NULL,
  "CC" VARCHAR(30) NOT NULL,
  PRIMARY KEY ("Mes", "Año", "FechaActualCompra", "CC"),
  CONSTRAINT "fk_PagoCréd_Fecha"
    FOREIGN KEY ("FechaActualCompra")
    REFERENCES "mydb"."Compra" ("FechaActual")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_PagoCréd_DNI"
    
    REFERENCES "mydb"."ClienteCred" ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DELIMITER $$
CREATE DEFINER = CURRENT_USER TRIGGER "mydb"."MedicamCompra_AFTER_INSERT" AFTER INSERT ON "MedicamCompra" FOR EACH ROW
BEGIN
	
    
    INSERT INTO Compra(FechaActual,Importe) VALUES (FechaActualCompra,(importe * (igic/100)));;
    
END$$


DELIMITER ;

