-- MySQL Script generated by MySQL Workbench
-- jue 07 nov 2019 12:53:11 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Viveros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viveros` (
  `Coordenadas` VARCHAR(30) NOT NULL,
  `Localidad` VARCHAR(30) NULL,
  PRIMARY KEY (`Coordenadas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Coordenadas` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Nombre`, `Coordenadas`),
  INDEX `FK_Zona_Vivero_idx` (`Coordenadas` ASC),
  CONSTRAINT `FK_Zona_Vivero`
    FOREIGN KEY (`Coordenadas`)
    REFERENCES `mydb`.`Viveros` (`Coordenadas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` INT NOT NULL,
  `Sueldo` FLOAT NULL,
  `CSS` INT NULL,
  `Antiguedad` DATE NULL,
  `Ventas` INT NULL,
  `FechaIni` DATE NOT NULL,
  `FechaFin` DATE NULL,
  `Coordenadas` VARCHAR(30) NULL,
  `Nombre` VARCHAR(20) NULL,
  PRIMARY KEY (`DNI`, `FechaIni`),
  INDEX `fk_Empleado_Zona_idx` (`Coordenadas` ASC),
  INDEX `fk_Empleado_ZonaNombre_idx` (`Nombre` ASC),
  CONSTRAINT `fk_Empleado_ZonaCoordenada`
    FOREIGN KEY (`Coordenadas`)
    REFERENCES `mydb`.`Zona` (`Coordenadas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_ZonaNombre`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Bonus` VARCHAR(30) NULL,
  `CompraMensual` FLOAT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `CodProducto` INT NOT NULL,
  `Precio` INT NULL,
  `Stock` INT NULL,
  PRIMARY KEY (`CodProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZonaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZonaProducto` (
  `Coordenadas` VARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `CodProducto` INT NOT NULL,
  `StockZona` INT NULL,
  PRIMARY KEY (`Coordenadas`, `Nombre`, `CodProducto`),
  INDEX `fk_ZonaProducto_Prod_idx` (`CodProducto` ASC),
  INDEX `fk_ZonaProducto_ZonaNombre_idx` (`Nombre` ASC),
  CONSTRAINT `fk_ZonaProducto_ZonaCoord`
    FOREIGN KEY (`Coordenadas`)
    REFERENCES `mydb`.`Zona` (`Coordenadas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ZonaProducto_Prod`
    FOREIGN KEY (`CodProducto`)
    REFERENCES `mydb`.`Producto` (`CodProducto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ZonaProducto_ZonaNombre`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClienEmpleProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClienEmpleProd` (
  `DNIEmp` INT NOT NULL,
  `DNIClien` INT NOT NULL,
  `CodProducto` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Cantidad` INT NULL,
  `FechaIni` DATE NULL,
  PRIMARY KEY (`DNIEmp`, `DNIClien`, `CodProducto`, `Fecha`),
  INDEX `fk_ClienEmpleProd_Clie _idx` (`DNIClien` ASC),
  INDEX `fk_ClienEmpleProd_Prod_idx` (`CodProducto` ASC),
  CONSTRAINT `fk_ClienEmpleProd_Emple`
    FOREIGN KEY (`DNIEmp`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienEmpleProd_Clie `
    FOREIGN KEY (`DNIClien`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienEmpleProd_Prod`
    FOREIGN KEY (`CodProducto`)
    REFERENCES `mydb`.`Producto` (`CodProducto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
