-- MySQL Script generated by MySQL Workbench
-- mie 13 nov 2019 19:01:08 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table farmacia.Familia
-- -----------------------------------------------------
CREATE TABLE  Familia (
  Nombre VARCHAR(45),
  Incompatibilidades VARCHAR(45) NULL,
  PRIMARY KEY (Nombre));


-- -----------------------------------------------------
-- Table farmacia.Enfermedad
-- -----------------------------------------------------
CREATE TABLE  Enfermedad (
  Nombre VARCHAR(45),
  Sintoma VARCHAR(45) NULL,
  PRIMARY KEY (Nombre));


-- -----------------------------------------------------
-- Table farmacia.FamiliaEnfermedad
-- -----------------------------------------------------
CREATE TABLE  FamiliaEnfermedad (
  Nombre_fam VARCHAR(45) REFERENCES Familia(Nombre) ON DELETE RESTRICT ON DELETE CASCADE,
  Nombre_enf VARCHAR(45) REFERENCES Enfermedad(Nombre) ON DELETE RESTRICT ON DELETE CASCADE,
  PRIMARY KEY (Nombre_fam, Nombre_enf));


-- -----------------------------------------------------
-- Table farmacia.Laboratio
-- -----------------------------------------------------
CREATE TABLE  Laboratio (
  Codigo INT,
  Nombre VARCHAR(45) NULL,
  Contacto VARCHAR(45) NULL,
  Telefono INT NULL,
  Calle VARCHAR(45) NULL,
  NumCalle INT NULL,
  CP INT NULL,
  PRIMARY KEY (Codigo));


-- -----------------------------------------------------
-- Table farmacia.Medicamento
-- -----------------------------------------------------
CREATE TABLE  Medicamento (
  Codigo INT,
  Nombre VARCHAR(45) NULL,
  Posologia VARCHAR(45) NULL,
  Igic% INT NULL,
  Precio INT NULL,
  Tipo BOOLEAN NOT NULL,
  Laboratorio INT NULL REFERENCES Laboratorio(codigo) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (Codigo));


-- -----------------------------------------------------
-- Table farmacia.MedicamFamilia
-- -----------------------------------------------------
CREATE TABLE  MedicamFamilia (
  CodigoMed INT NOT NULL REFERENCES Medicamento (Codigo) ON DELETE CASCADE ON UPDATE CASCADE,
  NombreFam VARCHAR(45) NOT NULL REFERENCES Familia (Nombre) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (CodigoMed, NombreFam));


-- -----------------------------------------------------
-- Table farmacia.Compra
-- -----------------------------------------------------
CREATE TABLE  Compra (
  FechaActual TIMESTAMP NOT NULL,
  Importe INT NULL,
  PRIMARY KEY (FechaActual));


-- -----------------------------------------------------
-- Table farmacia.MedicamCompra
-- -----------------------------------------------------
CREATE TABLE  MedicamCompra (
  CodigoMed INT NOT NULL REFERENCES Medicamento (Codigo) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FechaActualCompra TIMESTAMP NOT NULL REFERENCES Compra (FechaActual) ON DELETE NO ACTION ON UPDATE NO ACTION,
  Importe FLOAT NULL,
  Igic FLOAT NULL,
  PRIMARY KEY (CodigoMed, FechaActualCompra));


-- -----------------------------------------------------
-- Table farmacia.ClienteCred
-- -----------------------------------------------------
CREATE TABLE  ClienteCred (
  CC VARCHAR(30) NOT NULL,
  Nombre VARCHAR(45) NULL,
  DiaPago INT NULL,
  PRIMARY KEY (CC));


-- -----------------------------------------------------
-- Table farmacia.PagoCred
-- -----------------------------------------------------
CREATE TABLE  PagoCred (
  Mes INT NOT NULL,
  Año INT NOT NULL,
  FechaActualCompra TIMESTAMP NOT NULL REFERENCES Compra (FechaActual) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FechaPago TIMESTAMP NULL,
  CantidadPago FLOAT NULL,
  CC VARCHAR(30) NOT NULL REFERENCES CLienteCred (CC) ON DELETE NO ACTION ON UPDATE NO ACTION,
  PRIMARY KEY (Mes, Año, FechaActualCompra, CC));


DELIMITER $$
CREATE DEFINER = CURRENT_USER TRIGGER farmacia.MedicamCompra_AFTER_INSERT AFTER INSERT ON MedicamCompra FOR EACH ROW
BEGIN
	
    
    INSERT INTO Compra(FechaActual,Importe) VALUES (FechaActualCompra,(importe * (igic/100)));;
    
END$$


DELIMITER ;

