-- MySQL Script generated by MySQL Workbench
-- jue 07 nov 2019 12:53:11 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "mydb"  ;

-- -----------------------------------------------------
-- Table "mydb"."Viveros"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Viveros" (
  "Coordenadas" VARCHAR(30) NOT NULL,
  "Localidad" VARCHAR(30) NULL,
  PRIMARY KEY ("Coordenadas"));


-- -----------------------------------------------------
-- Table "mydb"."Zona"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Zona" (
  "Nombre" VARCHAR(20) NOT NULL,
  "Coordenadas" VARCHAR(30) NOT NULL,
  PRIMARY KEY ("Nombre", "Coordenadas"),
  CONSTRAINT "FK_Zona_Vivero"
    FOREIGN KEY ("Coordenadas")
    REFERENCES "mydb"."Viveros" ("Coordenadas")
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."Empleado"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Empleado" (
  "DNI" INT NOT NULL,
  "Sueldo" FLOAT NULL,
  "CSS" INT NULL,
  "Antiguedad" DATE NULL,
  "Ventas" INT NULL,
  "FechaIni" DATE NOT NULL,
  "FechaFin" DATE NULL,
  "Coordenadas" VARCHAR(30) NULL,
  "Nombre" VARCHAR(20) NULL,
  PRIMARY KEY ("DNI", "FechaIni"),
  CONSTRAINT "fk_Empleado_ZonaCoordenada"
    FOREIGN KEY ("Coordenadas")
    REFERENCES "mydb"."Zona" ("Coordenadas")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "fk_Empleado_ZonaNombre"
    FOREIGN KEY ("Nombre")
    REFERENCES "mydb"."Zona" ("Nombre")
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."Cliente"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Cliente" (
  "DNI" INT NOT NULL,
  "Bonus" VARCHAR(30) NULL,
  "CompraMensual" FLOAT NULL,
  PRIMARY KEY ("DNI"));


-- -----------------------------------------------------
-- Table "mydb"."Producto"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."Producto" (
  "CodProducto" INT NOT NULL,
  "Precio" INT NULL,
  "Stock" INT NULL,
  PRIMARY KEY ("CodProducto"));


-- -----------------------------------------------------
-- Table "mydb"."ZonaProducto"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."ZonaProducto" (
  "Coordenadas" VARCHAR(30) NOT NULL,
  "Nombre" VARCHAR(20) NOT NULL,
  "CodProducto" INT NOT NULL,
  "StockZona" INT NULL,
  PRIMARY KEY ("Coordenadas", "Nombre", "CodProducto"),
  CONSTRAINT "fk_ZonaProducto_ZonaCoord"
    FOREIGN KEY ("Coordenadas")
    REFERENCES "mydb"."Zona" ("Coordenadas")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "fk_ZonaProducto_Prod"
    FOREIGN KEY ("CodProducto")
    REFERENCES "mydb"."Producto" ("CodProducto")
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT "fk_ZonaProducto_ZonaNombre"
    FOREIGN KEY ("Nombre")
    REFERENCES "mydb"."Zona" ("Nombre")
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table "mydb"."ClienEmpleProd"
-- -----------------------------------------------------
CREATE TABLE  "mydb"."ClienEmpleProd" (
  "DNIEmp" INT NOT NULL,
  "DNIClien" INT NOT NULL,
  "CodProducto" INT NOT NULL,
  "Fecha" DATE NOT NULL,
  "Cantidad" INT NULL,
  "FechaIni" DATE NULL,
  PRIMARY KEY ("DNIEmp", "DNIClien", "CodProducto", "Fecha"),
  CONSTRAINT "fk_ClienEmpleProd_Emple"
    FOREIGN KEY ("DNIEmp")
    REFERENCES "mydb"."Empleado" ("DNI")
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT "fk_ClienEmpleProd_Clie "
    FOREIGN KEY ("DNIClien")
    REFERENCES "mydb"."Cliente" ("DNI")
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT "fk_ClienEmpleProd_Prod"
    FOREIGN KEY ("CodProducto")
    REFERENCES "mydb"."Producto" ("CodProducto")
    ON DELETE NO ACTION
    ON UPDATE CASCADE);


